export interface Env {
  AI: Ai;
  // All optional: only present once you opt in via `wrangler kv namespace create`
  // and `wrangler secret put` — see worker/README.md. Absent = the related feature
  // silently no-ops (chat logging) or 501s (view counts, reactions, testimonial submissions).
  CHAT_LOG?: KVNamespace;
  ADMIN_KEY?: string;
  VIEWS?: KVNamespace;
  // A fine-grained GitHub PAT with Contents read/write on this one repo — required
  // only for /testimonials/submit. Generated by the repo owner, never by the Worker.
  CONTENT_PAT?: string;
}

const REPO_OWNER = "developerhridu";
const CONTENT_BASE = `https://raw.githubusercontent.com/${REPO_OWNER}/developerhridu.github.io/main/content`;
const ALLOWED_ORIGINS = ["https://developerhridu.github.io", "http://localhost:3000"];
const MODEL = "@cf/meta/llama-3.1-8b-instruct-fast";

function corsHeaders(request: Request): HeadersInit {
  const origin = request.headers.get("Origin");
  const allowedOrigin = origin && ALLOWED_ORIGINS.includes(origin) ? origin : ALLOWED_ORIGINS[0];
  return {
    "Access-Control-Allow-Origin": allowedOrigin,
    "Access-Control-Allow-Methods": "POST, GET, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type, Authorization",
    Vary: "Origin",
  };
}

async function logQa(env: Env, question: string, answer: string) {
  if (!env.CHAT_LOG) return;
  try {
    const key = `qa:${Date.now()}:${crypto.randomUUID()}`;
    await env.CHAT_LOG.put(
      key,
      JSON.stringify({ question, answer, timestamp: new Date().toISOString() }),
      { expirationTtl: 60 * 60 * 24 * 90 } // keep 90 days
    );
  } catch {
    // Best-effort logging only — never let this affect the actual chat response.
  }
}

/** True if `token` is a valid GitHub token belonging to the repo owner — lets the admin
 *  panel reuse the same GitHub PAT it already collected instead of a separate secret. */
async function isRepoOwnerToken(token: string): Promise<boolean> {
  try {
    const res = await fetch("https://api.github.com/user", {
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: "application/vnd.github+json",
        "User-Agent": "hridu-portfolio-ai-chat-worker",
      },
    });
    if (!res.ok) return false;
    const data = await res.json<{ login?: string }>();
    return data.login === REPO_OWNER;
  } catch {
    return false;
  }
}

async function handleLogs(request: Request, env: Env): Promise<Response> {
  if (!env.CHAT_LOG) {
    return new Response(JSON.stringify({ error: "Logging is not configured for this Worker" }), {
      status: 501,
      headers: { "Content-Type": "application/json", ...corsHeaders(request) },
    });
  }

  const token = request.headers.get("Authorization")?.replace(/^Bearer\s+/i, "");
  const isAdminKey = !!token && !!env.ADMIN_KEY && token === env.ADMIN_KEY;
  const isAuthorized = isAdminKey || (!!token && (await isRepoOwnerToken(token)));

  if (!isAuthorized) {
    return new Response(JSON.stringify({ error: "Unauthorized" }), {
      status: 401,
      headers: { "Content-Type": "application/json", ...corsHeaders(request) },
    });
  }

  const list = await env.CHAT_LOG.list({ prefix: "qa:", limit: 100 });
  const sortedKeys = [...list.keys].sort((a, b) => b.name.localeCompare(a.name));
  const entries = await Promise.all(
    sortedKeys.map(async (k) => {
      const value = await env.CHAT_LOG!.get(k.name);
      return value ? JSON.parse(value) : null;
    })
  );

  return new Response(JSON.stringify({ entries: entries.filter(Boolean) }), {
    headers: { "Content-Type": "application/json", ...corsHeaders(request) },
  });
}

type ViewType = "blog" | "case-study";

function isViewType(v: unknown): v is ViewType {
  return v === "blog" || v === "case-study";
}

/**
 * Tracks per-slug reader counts in KV. GET just reads the current count (used by
 * listing pages, never increments). POST increments then returns the new count —
 * called once per browser per article, deduped client-side via localStorage.
 */
async function handleViews(request: Request, env: Env): Promise<Response> {
  if (!env.VIEWS) {
    return new Response(JSON.stringify({ error: "View counting is not configured for this Worker" }), {
      status: 501,
      headers: { "Content-Type": "application/json", ...corsHeaders(request) },
    });
  }

  const url = new URL(request.url);
  let type: string | null;
  let slug: string | null;

  if (request.method === "GET") {
    type = url.searchParams.get("type");
    slug = url.searchParams.get("slug");
  } else {
    try {
      const body = await request.json<{ type?: string; slug?: string }>();
      type = body.type ?? null;
      slug = body.slug ?? null;
    } catch {
      type = null;
      slug = null;
    }
  }

  if (!isViewType(type) || !slug) {
    return new Response(
      JSON.stringify({ error: "type must be 'blog' or 'case-study', and slug is required" }),
      { status: 400, headers: { "Content-Type": "application/json", ...corsHeaders(request) } }
    );
  }

  const key = `views:${type}:${slug}`;
  let count = Number((await env.VIEWS.get(key)) ?? "0") || 0;

  if (request.method === "POST") {
    count += 1;
    await env.VIEWS.put(key, String(count));
  }

  return new Response(JSON.stringify({ count }), {
    headers: { "Content-Type": "application/json", ...corsHeaders(request) },
  });
}

/**
 * Bulk view counts for a content type — powers "Most Read" widgets and the admin
 * dashboard's total-views stat. Never increments, just reads and ranks.
 */
async function handleViewsTop(request: Request, env: Env): Promise<Response> {
  if (!env.VIEWS) {
    return new Response(JSON.stringify({ error: "View counting is not configured for this Worker" }), {
      status: 501,
      headers: { "Content-Type": "application/json", ...corsHeaders(request) },
    });
  }

  const url = new URL(request.url);
  const typeParam = url.searchParams.get("type");
  const limit = Math.min(Math.max(Number(url.searchParams.get("limit")) || 5, 1), 20);
  const prefix = isViewType(typeParam) ? `views:${typeParam}:` : "views:";

  const list = await env.VIEWS.list({ prefix });
  const items = await Promise.all(
    list.keys.map(async (k) => {
      const value = await env.VIEWS!.get(k.name);
      const [, itemType, ...slugParts] = k.name.split(":");
      return { type: itemType, slug: slugParts.join(":"), count: Number(value) || 0 };
    })
  );

  const total = items.reduce((sum, i) => sum + i.count, 0);
  const top = [...items].sort((a, b) => b.count - a.count).slice(0, limit);

  return new Response(JSON.stringify({ items: top, total }), {
    headers: { "Content-Type": "application/json", ...corsHeaders(request) },
  });
}

/**
 * Toggleable per-visitor reaction counter ("was this helpful"), same KV store as
 * views under a different key prefix. POST action "add" increments, "remove"
 * decrements (floored at 0) — the client toggles state via localStorage.
 */
async function handleReactions(request: Request, env: Env): Promise<Response> {
  if (!env.VIEWS) {
    return new Response(JSON.stringify({ error: "Reactions are not configured for this Worker" }), {
      status: 501,
      headers: { "Content-Type": "application/json", ...corsHeaders(request) },
    });
  }

  const url = new URL(request.url);
  let type: string | null;
  let slug: string | null;
  let action: string | null = null;

  if (request.method === "GET") {
    type = url.searchParams.get("type");
    slug = url.searchParams.get("slug");
  } else {
    try {
      const body = await request.json<{ type?: string; slug?: string; action?: string }>();
      type = body.type ?? null;
      slug = body.slug ?? null;
      action = body.action ?? null;
    } catch {
      type = null;
      slug = null;
    }
  }

  if (!isViewType(type) || !slug) {
    return new Response(
      JSON.stringify({ error: "type must be 'blog' or 'case-study', and slug is required" }),
      { status: 400, headers: { "Content-Type": "application/json", ...corsHeaders(request) } }
    );
  }

  const key = `reactions:${type}:${slug}`;
  let count = Number((await env.VIEWS.get(key)) ?? "0") || 0;

  if (request.method === "POST") {
    count = action === "remove" ? Math.max(0, count - 1) : count + 1;
    await env.VIEWS.put(key, String(count));
  }

  return new Response(JSON.stringify({ count }), {
    headers: { "Content-Type": "application/json", ...corsHeaders(request) },
  });
}

function slugifyName(name: string): string {
  return (
    name
      .toLowerCase()
      .trim()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/(^-|-$)/g, "") || "submission"
  );
}

interface TestimonialSubmission {
  name?: string;
  role?: string;
  company?: string;
  email?: string;
  linkedinUrl?: string;
  quote?: string;
  honeypot?: string;
}

/**
 * Lets visitors submit their own testimonial. Lands in content/testimonials.json
 * as `published: false` — the admin's existing Testimonials tab is the review
 * queue, nothing goes live without a manual approve. Requires CONTENT_PAT (a
 * fine-grained GitHub PAT with Contents read/write on this repo only) since a
 * public endpoint can't use the admin's own session token.
 */
async function handleTestimonialSubmit(request: Request, env: Env): Promise<Response> {
  if (!env.CONTENT_PAT) {
    return new Response(
      JSON.stringify({ error: "Testimonial submissions are not configured for this Worker" }),
      { status: 501, headers: { "Content-Type": "application/json", ...corsHeaders(request) } }
    );
  }

  let body: TestimonialSubmission;
  try {
    body = await request.json<TestimonialSubmission>();
  } catch {
    return new Response(JSON.stringify({ error: "Invalid request body" }), {
      status: 400,
      headers: { "Content-Type": "application/json", ...corsHeaders(request) },
    });
  }

  // Honeypot: a hidden field real visitors never fill in. Pretend success to bots.
  if (body.honeypot) {
    return new Response(JSON.stringify({ ok: true }), {
      headers: { "Content-Type": "application/json", ...corsHeaders(request) },
    });
  }

  const name = (body.name ?? "").trim().slice(0, 100);
  const quote = (body.quote ?? "").trim().slice(0, 2000);
  const email = (body.email ?? "").trim().slice(0, 200);
  const role = (body.role ?? "").trim().slice(0, 100);
  const company = (body.company ?? "").trim().slice(0, 100);
  const linkedinUrl = (body.linkedinUrl ?? "").trim().slice(0, 300);

  if (!name || !quote || !email) {
    return new Response(JSON.stringify({ error: "Name, email, and quote are required" }), {
      status: 400,
      headers: { "Content-Type": "application/json", ...corsHeaders(request) },
    });
  }

  const path = "content/testimonials.json";
  const apiUrl = `https://api.github.com/repos/${REPO_OWNER}/developerhridu.github.io/contents/${path}`;
  const ghHeaders = {
    Authorization: `Bearer ${env.CONTENT_PAT}`,
    Accept: "application/vnd.github+json",
    "User-Agent": "hridu-portfolio-ai-chat-worker",
  };

  try {
    const getRes = await fetch(`${apiUrl}?ref=main`, { headers: ghHeaders });
    if (!getRes.ok) throw new Error("Could not read testimonials file");
    const fileData = await getRes.json<{ content: string; sha: string }>();
    const decoded = decodeURIComponent(escape(atob(fileData.content)));
    const parsed = JSON.parse(decoded) as { testimonials: Array<Record<string, unknown>> };

    const baseSlug = slugifyName(name);
    const existingIds = new Set(parsed.testimonials.map((t) => t.id));
    let id = baseSlug;
    let n = 2;
    while (existingIds.has(id)) {
      id = `${baseSlug}-${n}`;
      n++;
    }

    const newEntry: Record<string, unknown> = {
      id,
      name,
      quote,
      email,
      verifyImages: [],
      published: false,
    };
    if (role) newEntry.role = role;
    if (company) newEntry.company = company;
    if (linkedinUrl) newEntry.linkedinUrl = linkedinUrl;
    parsed.testimonials.push(newEntry);

    const newContent = JSON.stringify(parsed, null, 2) + "\n";
    const encoded = btoa(unescape(encodeURIComponent(newContent)));

    const putRes = await fetch(apiUrl, {
      method: "PUT",
      headers: { ...ghHeaders, "Content-Type": "application/json" },
      body: JSON.stringify({
        message: `content: testimonial submission from ${name}`,
        content: encoded,
        sha: fileData.sha,
        branch: "main",
      }),
    });

    if (!putRes.ok) throw new Error("Could not save testimonial");

    return new Response(JSON.stringify({ ok: true }), {
      headers: { "Content-Type": "application/json", ...corsHeaders(request) },
    });
  } catch {
    return new Response(JSON.stringify({ error: "Submission failed. Please try again later." }), {
      status: 502,
      headers: { "Content-Type": "application/json", ...corsHeaders(request) },
    });
  }
}

async function fetchJson(path: string): Promise<unknown> {
  try {
    const res = await fetch(`${CONTENT_BASE}/${path}`, {
      cf: { cacheTtl: 300, cacheEverything: true },
    });
    if (!res.ok) return null;
    return await res.json();
  } catch {
    return null;
  }
}

interface ProfileData {
  name: string;
  title: string;
  tagline: string;
  bio: string;
  location: string;
  yearsOfExperience: number;
  email: string;
  social?: { github?: string; linkedin?: string };
}

interface ExperienceProject {
  name: string;
  description?: string;
  technologies?: string[];
  highlights?: string[];
}

interface ExperienceEntry {
  role: string;
  company: string;
  period: string;
  location?: string;
  projects?: ExperienceProject[];
}

interface ProjectEntry {
  title: string;
  description: string;
  tags?: string[];
}

interface EducationEntry {
  degree: string;
  institution: string;
  period: string;
}

interface CertificationEntry {
  name: string;
  issuer: string;
  date: string;
}

interface PostEntry {
  title: string;
  description: string;
  published?: boolean;
}

async function buildContext(): Promise<string> {
  const [profile, experience, projects, techStack, education, certifications, blogs, caseStudies] =
    await Promise.all([
      fetchJson("profile.json"),
      fetchJson("experience.json"),
      fetchJson("projects.json"),
      fetchJson("tech-stack.json"),
      fetchJson("education.json"),
      fetchJson("certifications.json"),
      fetchJson("blogs.json"),
      fetchJson("case-studies.json"),
    ]);

  const parts: string[] = [];

  if (profile) {
    const p = profile as ProfileData;
    parts.push(
      `NAME: ${p.name}\nTITLE: ${p.title}\nTAGLINE: ${p.tagline}\nBIO: ${p.bio}\nLOCATION: ${p.location}\nYEARS OF EXPERIENCE: ${p.yearsOfExperience}\nEMAIL: ${p.email}\nGITHUB: ${p.social?.github ?? ""}\nLINKEDIN: ${p.social?.linkedin ?? ""}`
    );
  }

  if (experience) {
    const exps = ((experience as { experiences?: ExperienceEntry[] }).experiences ?? []);
    const text = exps
      .map((e) => {
        const projectsText = (e.projects ?? [])
          .map(
            (proj) =>
              `  - ${proj.name}: ${proj.description ?? ""} Tech: ${(proj.technologies ?? []).join(", ")}. Highlights: ${(proj.highlights ?? []).join("; ")}`
          )
          .join("\n");
        return `${e.role} at ${e.company} (${e.period}, ${e.location ?? ""})\n${projectsText}`;
      })
      .join("\n\n");
    parts.push(`EXPERIENCE:\n${text}`);
  }

  if (projects) {
    const projs = (projects as { projects?: ProjectEntry[] }).projects ?? [];
    const text = projs
      .map((p) => `- ${p.title}: ${p.description} (Tech: ${(p.tags ?? []).join(", ")})`)
      .join("\n");
    parts.push(`PERSONAL/FEATURED PROJECTS:\n${text}`);
  }

  if (techStack) {
    const t = techStack as Record<string, string[]>;
    const text = Object.entries(t)
      .map(([k, v]) => `${k}: ${v.join(", ")}`)
      .join("\n");
    parts.push(`TECH STACK:\n${text}`);
  }

  if (education) {
    const edu = (education as { education?: EducationEntry[] }).education ?? [];
    const text = edu.map((e) => `- ${e.degree}, ${e.institution} (${e.period})`).join("\n");
    parts.push(`EDUCATION:\n${text}`);
  }

  if (certifications) {
    const certs = (certifications as { certifications?: CertificationEntry[] }).certifications ?? [];
    const text = certs.map((c) => `- ${c.name} (${c.issuer}, ${c.date})`).join("\n");
    parts.push(`CERTIFICATIONS:\n${text}`);
  }

  if (blogs) {
    const posts = (blogs as { posts?: PostEntry[] }).posts ?? [];
    const text = posts
      .filter((p) => p.published !== false)
      .map((p) => `- ${p.title}: ${p.description}`)
      .join("\n");
    if (text) parts.push(`BLOG POSTS:\n${text}`);
  }

  if (caseStudies) {
    const studies = (caseStudies as { caseStudies?: PostEntry[] }).caseStudies ?? [];
    const text = studies
      .filter((s) => s.published !== false)
      .map((s) => `- ${s.title}: ${s.description}`)
      .join("\n");
    if (text) parts.push(`CASE STUDIES:\n${text}`);
  }

  return parts.join("\n\n");
}

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);

    if (request.method === "OPTIONS") {
      return new Response(null, { headers: corsHeaders(request) });
    }

    if (request.method === "GET" && url.pathname === "/logs") {
      return handleLogs(request, env);
    }

    if (request.method === "GET" && url.pathname === "/views/top") {
      return handleViewsTop(request, env);
    }

    if ((request.method === "GET" || request.method === "POST") && url.pathname === "/views") {
      return handleViews(request, env);
    }

    if ((request.method === "GET" || request.method === "POST") && url.pathname === "/reactions") {
      return handleReactions(request, env);
    }

    if (request.method === "POST" && url.pathname === "/testimonials/submit") {
      return handleTestimonialSubmit(request, env);
    }

    if (request.method !== "POST") {
      return new Response("Method not allowed", { status: 405, headers: corsHeaders(request) });
    }

    let question: string;
    let history: { role: "user" | "assistant"; content: string }[];
    try {
      const body = await request.json<{
        question?: string;
        history?: { role?: string; content?: string }[];
      }>();
      question = (body.question ?? "").trim().slice(0, 500);
      history = Array.isArray(body.history)
        ? body.history
            .filter(
              (m): m is { role: "user" | "assistant"; content: string } =>
                (m.role === "user" || m.role === "assistant") && typeof m.content === "string"
            )
            .slice(-6)
            .map((m) => ({ role: m.role, content: m.content.slice(0, 500) }))
        : [];
    } catch {
      return new Response(JSON.stringify({ error: "Invalid request body" }), {
        status: 400,
        headers: { "Content-Type": "application/json", ...corsHeaders(request) },
      });
    }

    if (!question) {
      return new Response(JSON.stringify({ error: "Question is required" }), {
        status: 400,
        headers: { "Content-Type": "application/json", ...corsHeaders(request) },
      });
    }

    const context = await buildContext();

    const systemPrompt = `You are a friendly assistant on Mizanur Rahman's portfolio website. Answer visitor questions about Mizanur using ONLY the information below. Speak about him in the third person. Be concise (3-5 sentences max unless listing items). If asked something not covered by this information, say you don't have that detail and suggest the visitor use the Contact page. Do not make up facts.\n\n${context}`;

    try {
      const result = await env.AI.run(MODEL, {
        messages: [
          { role: "system", content: systemPrompt },
          ...history,
          { role: "user", content: question },
        ],
      });

      const answer =
        (result as { response?: string }).response?.trim() ||
        "Sorry, I couldn't come up with an answer to that.";

      ctx.waitUntil(logQa(env, question, answer));

      return new Response(JSON.stringify({ answer }), {
        headers: { "Content-Type": "application/json", ...corsHeaders(request) },
      });
    } catch {
      return new Response(JSON.stringify({ error: "AI request failed" }), {
        status: 502,
        headers: { "Content-Type": "application/json", ...corsHeaders(request) },
      });
    }
  },
};
