name = "hridu-portfolio-ai-chat"
main = "src/index.ts"
compatibility_date = "2024-11-01"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "CHAT_LOG"
id = "d3599f06d98e46a3ba18bc828906d585"

[[kv_namespaces]]
binding = "VIEWS"
id = "cf657ad7c926419494059ca9239f693c"
